---
title: "In-Class Exercise 4 - Isopleth Map for Rainfall Data"
date: "March 9 , 2024"
date-modified: "last-modified"
toc: true
execute: 
  eval: true
  echo: true
  message: false
  warning: false
---

# Getting Started

## Loading R package and Importing Data

```{r}
pacman::p_load(sf, terra, gstat, tmap,
               viridis, tidyverse)
```

```{r}
rfstation <- read_csv("data/aspatial/RainfallStation.csv")
```

```{r}
rfdata <- read_csv("data/aspatial/DAILYDATA_202402.csv") %>%
  select(Station, `Daily Rainfall Total (mm)`) %>%  
  group_by(Station) %>%
  summarise(MONTHSUM = sum(`Daily Rainfall Total (mm)`, na.rm = TRUE)) %>%
  ungroup()
```

```{r}
rfdata <-  rfdata%>%
  left_join(rfstation)
```

```{r}
rfdata_sf <- st_as_sf(rfdata,
                      coords = c("Longitude",
                                 "Latitude"),
                      crs = 4326) %>%
  st_transform(crs = 3414)
```

```{r}
mpsz2019 <- st_read(dsn = "data/geospatial",
                    layer = "MPSZ-2019") %>%
  st_transform(crs = 3414)
```

```{r}
tmap_options(check.and.fix = TRUE )
tmap_mode("view")
tm_shape(mpsz2019) +
  tm_borders() +
  tm_shape(rfdata_sf) +
  tm_dots(col = 'MONTHSUM')
tmap_mode("plot")
```

```{r}
grid <- terra::rast(mpsz2019,
                   nrows = 690,
                   ncols = 1075)

xy <- terra::xyFromCell(grid,
                        1:ncell(grid))
```

```{r}
#coop <- st_as_sf
```
