project:
  type: website

website:
  title: "Imran's Visual Analytics page"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1 - A Layered Grammar of Graphics:ggplot2 methods
            href: Hands-on-ex/Hands-on-Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 2 - Beyond ggplot2 fundamentals
            href: Hands-on-ex/Hands-on-Ex2/Hands-on_Ex2.html
          - text: Hands-on Exercise 3a - Programming Interactive Data Visualisation with R
            href: Hands-on-ex/Hands-on-Ex3a/Hands-on_Ex3a.html
          - text: Hands-on Exercise 3b - Programming Animated Statistical Graphics with R
            href: Hands-on-ex/Hands-on-Ex3b/Hands-on_Ex3b.html
          - text: Hands-on Exercise 4a - Visualising Distribution
            href: Hands-on-ex/Hands-on-Ex4a/Hands-on_Ex4a.html
          - text: Hands-on Exercise 4b - Visual Stasticial Analysis
            href: Hands-on-ex/Hands-on-Ex4b/Hands-on_Ex4b.html
          - text: Hands-on Exercise 4c - Visualising Uncertainty
            href: Hands-on-ex/Hands-on-Ex4c/Hands-on_Ex4c.html
          - text: Hands-on Exercise 4d - Funnel Plots for Fair Comparisons
            href: Hands-on-ex/Hands-on-Ex4d/Hands-on_Ex4d.html
          - text: Hands-on Exercise 5a - Building Ternary Plots with R
            href: Hands-on-ex/Hands-on-Ex5a/Hands-on_Ex5a.html
          - text: Hands-on Exercise 5b - Visual Correlation Analysis
            href: Hands-on-ex/Hands-on-Ex5b/Hands-on_Ex5b.html
          - text: Hands-on Exercise 5c - Visual Multivariate Analysis with Heatmap
            href: Hands-on-ex/Hands-on-Ex5c/Hands-on_Ex5c.html
          - text: Hands-on Exercise 5d - Visual Multivariate Analysis with Parallel Coordinates Plot
            href: Hands-on-ex/Hands-on-Ex5d/Hands-on_Ex5d.html
          - text: Hands-on Exercise 5e - Treemap Visualisation with R
            href: Hands-on-ex/Hands-on-Ex5e/Hands-on_Ex5e.html
          - text: Hands-on Exercise 6 - Visualising and Analysing Time-oriented Data
            href: Hands-on-ex/Hands-on-Ex6/Hands-on_Ex6.html
          - text: Hands-on Exercise 7a - Chropleth Mapping in R
            href: Hands-on-ex/Hands-on-Ex7a/Hands-on_Ex7a.html
          - text: Hands-on Exercise 7b - Visualising Geospatial Point Data
            href: Hands-on-ex/Hands-on-Ex7b/Hands-on_Ex7b.html
          - text: Hands-on Exercise 7c - Analytical Mapping
            href: Hands-on-ex/Hands-on-Ex7c/Hands-on_Ex7c.html
          - text: Hands-on Exercise 8 - Modelling, Visualising and Analysing Network Data with R
            href: Hands-on-ex/Hands-on-Ex8/Hands-on_Ex8.html
          - text: Hands-on Exercise 9 - Visualising and Analysing Text Data
            href: Hands-on-ex/Hands-on-Ex9/Hands-on_Ex9.html
          - text: Hands-on Exercise 10 - Information Dashboard Design:R methods
            href: Hands-on-ex/Hands-on-Ex10/Hands-on_Ex10.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class-ex/In-class-Ex1/In-class_Ex1.html
          - text: In-class Exercise 2
            href: In-class-ex/In-class-Ex2/In-class_Ex2.html
          - text: In-class Exercise 3 - Horizon Plots
            href: In-class-ex/In-class-Ex3/In-class_Ex3.html
          - text: In-class Exercise 4
            href: In-class-ex/In-class-Ex4/In-class_Ex4.html
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1 - Detailed
            href: Take-home-ex/Take-home-Ex1/Take-home_Ex1.html
          - text: Take-home Exercise 1a - 5 EDAs
            href: Take-home-ex/Take-home-Ex1a/Take-home_Ex1a.html
          - text: Take-home Exercise 1b
            href: Take-home-ex/Take-home-Ex1b/Take-home_Ex1b.html
          - text: Take-home Exercise 2 - DataVis Makeover
            href: Take-home-ex/Take-home-Ex2/Take-home_Ex2.html
          - text: Take-home Exercise 3 - Be Weatherwise or Otherwise
            href: Take-home-ex/Take-home-Ex3/Take-home_Ex3.html
          - text: Take-home Exercise 4
            href: Take-home-ex/Take-home-Ex4/Take-home_Ex4.html
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual
